### ISSUE TITLE
parameter must be a descendant of this view

### ISSUE THREAD

**Issue by qinyang1018** [alibaba/UltraViewPager#28]
我把ultraviewpager放在列表的head上，设置UltraViewPager.setInfiniteLoop(true);  滑动轮播闪退，不加这个设置就没问题。
使用com.alibaba.android:ultraviewpager:1.0.3@aar
错误日志：
```
java.lang.IllegalArgumentException: parameter must be a descendant of this view
                                                                       at android.view.ViewGroup.offsetRectBetweenParentAndChild(ViewGroup.java:5515)
                                                                       at android.view.ViewGroup.offsetDescendantRectToMyCoords(ViewGroup.java:5444)
                                                                       at android.view.ViewGroup$ViewLocationHolder.init(ViewGroup.java:7935)
                                                                       at android.view.ViewGroup$ViewLocationHolder.obtain(ViewGroup.java:7869)
                                                                       at android.view.ViewGroup$ChildListForAccessibility.init(ViewGroup.java:7804)
                                                                       at android.view.ViewGroup$ChildListForAccessibility.obtain(ViewGroup.java:7772)
                                                                       at android.view.ViewGroup.addChildrenForAccessibility(ViewGroup.java:2015)
                                                                       at android.view.ViewGroup.onInitializeAccessibilityNodeInfoInternal(ViewGroup.java:3117)
                                                                       at android.view.View$AccessibilityDelegate.onInitializeAccessibilityNodeInfo(View.java:23632)
                                                                       at android.support.v4.view.AccessibilityDelegateCompatIcs.onInitializeAccessibilityNodeInfo(AccessibilityDelegateCompatIcs.java:101)
                                                                       at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateIcsImpl.onInitializeAccessibilityNodeInfo(AccessibilityDelegateCompat.java:198)
                                                                       at android.support.v4.view.AccessibilityDelegateCompat.onInitializeAccessibilityNodeInfo(AccessibilityDelegateCompat.java:451)
                                                                       at android.support.v4.view.ViewPager$MyAccessibilityDelegate.onInitializeAccessibilityNodeInfo(ViewPager.java:3069)
                                                                       at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateJellyBeanImpl$1.onInitializeAccessibilityNodeInfo(AccessibilityDelegateCompat.java:246)
                                                                       at android.support.v4.view.AccessibilityDelegateCompatJellyBean$1.onInitializeAccessibilityNodeInfo(AccessibilityDelegateCompatJellyBean.java:66)
                                                                       at android.view.View.onInitializeAccessibilityNodeInfo(View.java:6621)
                                                                       at android.view.View.createAccessibilityNodeInfoInternal(View.java:6582)
                                                                       at android.view.View$AccessibilityDelegate.createAccessibilityNodeInfo(View.java:23701)
                                                                       at android.view.View.createAccessibilityNodeInfo(View.java:6565)
                                                                       at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:145)
                                                                       at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:119)
                                                                       at android.view.View.onInitializeAccessibilityEventInternal(View.java:6519)
                                                                       at android.view.View$AccessibilityDelegate.onInitializeAccessibilityEvent(View.java:23613)
                                                                       at android.support.v4.view.AccessibilityDelegateCompatIcs.onInitializeAccessibilityEvent(AccessibilityDelegateCompatIcs.java:97)
                                                                       at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateIcsImpl.onInitializeAccessibilityEvent(AccessibilityDelegateCompat.java:192)
                                                                       at android.support.v4.view.AccessibilityDelegateCompat.onInitializeAccessibilityEvent(AccessibilityDelegateCompat.java:432)
                                                                       at android.support.v4.view.ViewPager$MyAccessibilityDelegate.onInitializeAccessibilityEvent(ViewPager.java:3054)
                                                                       at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateJellyBeanImpl$1.onInitializeAccessibilityEvent(AccessibilityDelegateCompat.java:241)
                                                                       at android.support.v4.view.AccessibilityDelegateCompatJellyBean$1.onInitializeAccessibilityEvent(AccessibilityDelegateCompatJellyBean.java:61)
                                                                       at android.view.View.onInitializeAccessibilityEvent(View.java:6505)
                                                                       at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:6368)
                                                                       at android.view.View$AccessibilityDelegate.sendAccessibilityEventUnchecked(View.java:23552)
                                                                       at android.support.v4.view.AccessibilityDelegateCompatIcs.sendAccessibilityEventUnchecked(AccessibilityDelegateCompatIcs.java:122)
                                                                       at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateIcsImpl.sendAccessibilityEventUnchecked(AccessibilityDelegateCompat.java:223)
                                                                       at android.support.v4.view.AccessibilityDelegateCompat.sendAccessibilityEventUnchecked(AccessibilityDelegateCompat.java:371)
                                                                       at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateJellyBeanImpl$1.sendAccessibilityEventUnchecked(AccessibilityDelegateCompat.java:268)
   at android.support.v4.view.AccessibilityDelegateCompatJellyBean$1.sendAccessibilityEventUnchecked(AccessibilityDelegateCompatJellyBean.java:87)
                                                                       at android.view.View.sendAccessibilityEventUnchecked(View.java:6351)
                                                                       at android.view.View.sendAccessibilityEventInternal(View.java:6330)
                                                                       at android.view.View$AccessibilityDelegate.sendAccessibilityEvent(View.java:23510)
                                                                       at android.support.v4.view.AccessibilityDelegateCompatIcs.sendAccessibilityEvent(AccessibilityDelegateCompatIcs.java:117)
                                                                       at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateIcsImpl.sendAccessibilityEvent(AccessibilityDelegateCompat.java:217)
                                                                       at android.support.v4.view.AccessibilityDelegateCompat.sendAccessibilityEvent(AccessibilityDelegateCompat.java:349)
                                                                       at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateJellyBeanImpl$1.sendAccessibilityEvent(AccessibilityDelegateCompat.java:263)
                                                                       at android.support.v4.view.AccessibilityDelegateCompatJellyBean$1.sendAccessibilityEvent(AccessibilityDelegateCompatJellyBean.java:82)
                                                                       at android.view.View.sendAccessibilityEvent(View.java:6295)
                                                                       at android.view.View$SendViewScrolledAccessibilityEvent.run(View.java:23416)
                                                                       at android.os.Handler.handleCallback(Handler.java:755)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:156)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6524)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
```

**Comment by MikeAfc** [comment]
[https://www.google.com/search?q=parameter+must+be+a+descendant+of+this+view&oq=parameter+must+be+a+descendant+of+this+view&aqs=chrome..69i57j69i60&sourceid=chrome&ie=UTF-8](Google result)，[http://www.eoeandroid.com/thread-908810-1-1.html](看下这个有没有帮助)

**Comment by pinocc** [comment]
我也遇到了类似的问题
