### ISSUE TITLE
question

### ISSUE THREAD

**Issue by zhuxiaogit** [alibaba/UltraViewPager#31]
` Process: com.tmall.ultraviewpager.sample, PID: 20920
                                                                                 java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 622, found: 623 Pager id: 1 Pager class: class com.tmall.ultraviewpager.UltraViewPagerView Problematic adapter: class com.tmall.ultraviewpager.UltraViewPagerAdapter
                                                                                     at android.support.v4.view.ViewPager.populate(ViewPager.java:1000)
                                                                                     at android.support.v4.view.ViewPager.populate(ViewPager.java:952)
                                                                                     at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1474)
                                                                                     at com.tmall.ultraviewpager.UltraViewPagerView.onMeasure(UltraViewPagerView.java:83)
                                                                                     at android.view.View.measure(View.java:17547)
                                                                                     at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:727)
                                                                                     at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:463)
                                                                                     at com.tmall.ultraviewpager.UltraViewPager.onMeasure(UltraViewPager.java:177)`

**Comment by MikeAfc** [comment]
麻烦贴下调用代码或简单描述下

**Comment by blackmamba123** [comment]
从log来看 throw new IllegalStateException("The application's PagerAdapter changed the adapter's" +
                    " contents without calling PagerAdapter#notifyDataSetChanged!" +
                    " Expected adapter item count: " + mExpectedAdapterCount + ", found: " + N +
                    " Pager id: " + resName +
                    " Pager class: " + getClass() +
                    " Problematic adapter: " + mAdapter.getClass());
是这段代码抛出的异常； 您可以看看 是不是多线程访问导致 或者看看 在一次更新过程中 ItemCount为什么会变化。
