### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by t1030338120** [alibaba/UltraViewPager#32]
布局中有UltraViewPager，进入界面必须第一时间设置一个Adaper，等一下设置就会崩溃

**Comment by MikeAfc** [comment]
贴下log看看

**Comment by zhudongya123** [comment]
我也遇到了相同情况，在onMeasure方法里面报错，此时Adapter为空。
```java
 FATAL EXCEPTION: main
 Process: cn.kashenbang.android, PID: 22730
 java.lang.NullPointerException: Attempt to invoke virtual method 'int com.tmall.ultraviewpager.UltraViewPagerAdapter.getCount()' on a null object reference
at com.tmall.ultraviewpager.UltraViewPagerView.getCurrentItem(UltraViewPagerView.java:220)
at com.tmall.ultraviewpager.UltraViewPagerView.onMeasurePage(UltraViewPagerView.java:88)
at com.tmall.ultraviewpager.UltraViewPagerView.onMeasure(UltraViewPagerView.java:84)
at android.view.View.measure(View.java:18811)
 at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:716)
at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:462)
at com.tmall.ultraviewpager.UltraViewPager.onMeasure(UltraViewPager.java:177)
at android.view.View.measure(View.java:18811)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
at android.view.View.measure(View.java:18811)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at android.support.design.widget.CollapsingToolbarLayout.onMeasure(CollapsingToolbarLayout.java:410)
at android.view.View.measure(View.java:18811)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)

```

**Comment by pinocc** [comment]
我也有一样的问题

**Comment by a512509050** [comment]
+1

**Comment by Jungle2329** [comment]
刚创建好的时候没有调用setAdapter崩溃 +1
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.tmall.ultraviewpager.UltraViewPagerAdapter.getCount()' on a null object reference
                                                                     at com.tmall.ultraviewpager.UltraViewPagerView.getCurrentItem(UltraViewPagerView.java:217)
                                                                     at com.tmall.ultraviewpager.UltraViewPagerView.onMeasurePage(UltraViewPagerView.java:86)
                                                                     at com.tmall.ultraviewpager.UltraViewPagerView.onMeasure(UltraViewPagerView.java:82)
                                                                     at android.view.View.measure(View.java:18811)
                                                                     at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:716)
                                                                     at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:462)
                                                                     at com.tmall.ultraviewpager.UltraViewPager.onMeasure(UltraViewPager.java:179)
                                                                     at android.view.View.measure(View.java:18811)
                                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:901)
                                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                     at android.view.View.measure(View.java:18811)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                     at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                     at android.view.View.measure(View.java:18811)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                     at android.view.View.measure(View.java:18811)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                     at android.view.View.measure(View.java:18811)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                     at android.view.View.measure(View.java:18811)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                     at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
                                                                     at android.view.View.measure(View.java:18811)
                                                                     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2127)
                                                                     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1243)
                                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1479)
                                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1134)
                                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6050)
                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:672)
                                                                     at android.view.Choreographer.doFrame(Choreographer.java:608)
                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
                                                                     at android.os.Handler.handleCallback(Handler.java:742)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5527)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                     at `com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)`

**Comment by MikeAfc** [comment]
建议在初始化adapter先设上，后面数据变化直接修改数据源，代码上不好做兼容，我会简单加个保护
