### ISSUE TITLE
 java.lang.NullPointerException: Attempt to invoke virtual method 'int com.tmall.ultraviewpager.UltraViewPagerAdapter.getCount()' on a null object reference

### ISSUE THREAD

**Issue by cs199111021521** [alibaba/UltraViewPager#35]
好像是因为布局文件嵌套太多吗？  尽量减少了布局嵌套就没有这个问题了。，想问下大神。具体的该如何避免这种错误呢，

java.lang.NullPointerException: Attempt to invoke virtual method 'int com.tmall.ultraviewpager.UltraViewPagerAdapter.getCount()' on a null object reference
                                                                       at com.tmall.ultraviewpager.UltraViewPagerView.getCurrentItem(UltraViewPagerView.java:220)
                                                                       at com.tmall.ultraviewpager.UltraViewPagerView.onMeasurePage(UltraViewPagerView.java:88)
                                                                       at com.tmall.ultraviewpager.UltraViewPagerView.onMeasure(UltraViewPagerView.java:84)
                                                                       at android.view.View.measure(View.java:20171)
                                                                       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:716)
                                                                       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:462)
                                                                       at com.tmall.ultraviewpager.UltraViewPager.onMeasure(UltraViewPager.java:177)
                                                                       at android.view.View.measure(View.java:20171)
                                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
                                                                       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                       at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
                                                                       at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
                                                                       at android.view.View.measure(View.java:20171)
                                                                       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:716)
                                                                       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:462)
                                                                       at android.view.View.measure(View.java:20171)
                                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
                                                                       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                       at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
                                                                       at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
                                                                       at android.view.View.measure(View.java:20171)
                                                                       at android.support.v7.widget.GridLayoutManager.measureChildWithDecorationsAndMargin(GridLayoutManager.java:724)
                                                                       at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:575)
                                                                       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1353)
                                                                       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:574)
                                                                       at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3028)
                                                                       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2906)
                                                                       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3283)
                                                                       at android.view.View.layout(View.java:17945)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                       at android.view.View.layout(View.java:17945)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
                                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                       at android.view.View.layout(View.java:17945)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                       at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1767)
                                                                       at android.view.View.layout(View.java:17945)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
                                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                       at android.view.View.layout(View.java:17945)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                       at android.view.View.layout(View.java:17945)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
                                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                       at android.view.View.layout(View.java:17945)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                   	at a

**Comment by kancic** [comment]
I have that to on Android 7.1.1 but not on Android 5.1.1

**Comment by hongming1218** [comment]
荣耀8  7.1 也遇到这个问题   数据源传进去  也是报null    你解决了没

**Comment by zhaoxiuyu** [comment]
我的也是这个问题，没有其他的代码，只是 添加xml 里面运行就报错，我的是红米

**Comment by daobenzhen** [comment]
我把这个添加到recyclerview的头布局中去也报了这个错误

**Comment by MikeAfc** [comment]
猜测是没有在UltraViewPager初始化的时候设置adapter引起，我会做修复，建议在初始化adapter先设上，后面数据变化直接修改数据源

**Comment by prasad456** [comment]
Its not working,
As I my code as yours.

**Comment by SamiraElhami** [comment]
try to put adapter in onCreate()
