### ISSUE TITLE
[bug] 首页的pagerAdapter内容改变并没有更新banner里的内容

### ISSUE THREAD

**Issue by ostea** [alibaba/UltraViewPager#37]
'''java
RequestServerTask: java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 800, found: 2000 Pager id: 2 Pager class: class com.tmall.ultraviewpager.UltraViewPagerView Problematic adapter: class com.tmall.ultraviewpager.UltraViewPagerAdapter
                                                                               at android.support.v4.view.ViewPager.populate(ViewPager.java:1134)
                                                                               at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:666)
                                                                               at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:628)
                                                                               at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:620)
                                                                               at com.tmall.ultraviewpager.UltraViewPagerView.setCurrentItem(UltraViewPagerView.java:215)
                                                                               at com.tmall.ultraviewpager.UltraViewPagerView.setCurrentItem(UltraViewPagerView.java:207)
                                                                               at com.tmall.ultraviewpager.UltraViewPager.setCurrentItem(UltraViewPager.java:419)
                                                                               at com.redteamobile.roaming.fragments.MainLocationFragment.notifyBanner(MainLocationFragment.java:405)
                                                                               at com.redteamobile.roaming.fragments.MainLocationFragment.refreshBanner(MainLocationFragment.java:362)
                                                                               at com.redteamobile.roaming.fragments.MainLocationFragment.onGetBanner(MainLocationFragment.java:430)
                                                                               at com.redteamobile.roaming.fragments.AllLocationsFragment$9.onSuccess(AllLocationsFragment.java:362)
                                                                               at com.redteamobile.roaming.fragments.AllLocationsFragment$9.onSuccess(AllLocationsFragment.java:349)
                                                                               at com.redteamobile.masterbase.remote.RequestServerTask.onPostExecute(RequestServerTask.java:33)
                                                                               at com.redteamobile.masterbase.remote.RequestServerTask.onPostExecute(RequestServerTask.java:10)
                                                                               at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                                               at android.os.AsyncTask.access$500(AsyncTask.java:180)
                                                                               at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:179)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5672)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)
'''

**Comment by ostea** [comment]
issue里面有好些类似的issue，假如有fix 请及时告知

**Comment by GITMrHu** [comment]
的确是，如果放在recycleview的头部局中时，当刷新数据源时，图片是不会变的，这个是我的操作不正确吗？我是直接调用的 pageradapter.notifyDataSetChanged();这样？

**Comment by GITMrHu** [comment]
I add it to topview of recycleview ,but when i refresh the date,the banner will never change ,am i ues the roung way? ( pageradapter.notifyDataSetChanged();   i use it like this )?

**Comment by MikeAfc** [comment]
Have added method to help refresh data. See faq to learn more:
https://github.com/alibaba/UltraViewPager/wiki/FAQ
https://github.com/alibaba/UltraViewPager#faq
