### ISSUE TITLE
Add items after calling setAdapter error: "The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged!" 

### ISSUE THREAD

**Issue by dimanem** [alibaba/UltraViewPager#69]
The exception:
```
 java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 0, found: 4 Pager id: 2 Pager class: class com.tmall.ultraviewpager.UltraViewPagerView Problematic adapter: class com.tmall.ultraviewpager.UltraViewPagerAdapter
                                                                                at android.support.v4.view.ViewPager.populate(ViewPager.java:1135)
                                                                                at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:662)
                                                                                at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:624)
                                                                                at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:616)
                                                                                at com.tmall.ultraviewpager.UltraViewPagerView.setCurrentItemFake(UltraViewPagerView.java:242)
                                                                                at com.tmall.ultraviewpager.UltraViewPager.scrollNextPage(UltraViewPager.java:379)
                                                                                at com.tmall.ultraviewpager.UltraViewPager$2.callBack(UltraViewPager.java:298)
                                                                                at com.tmall.ultraviewpager.TimerHandler.handleMessage(TimerHandler.java:61)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                at android.os.Looper.loop(Looper.java:164)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

Happens when trying to add views after adapter was already created using the following code:

```
//The adapter class
public class MyAdapter extends PagerAdapter {

    private Context mContext;
    private List<Object> mData = new ArrayList<>();

    public MyAdapter(@NonNull Context context) {
        mContext = context;
    }

    @Override
    public int getCount() {
        return mData.size();
    }

    // Trying to add data dynamically
    public void addData(@NonNull List<Object> data) {
        mData.addAll(data);
        notifyDataSetChanged();
    }

    @Override
    public Object instantiateItem(ViewGroup container, int position) {
        RelativeLayout contentContainer = new RelativeLayout(mContext);
        TextView textView = new TextView(mContext);
        textView.setGravity(Gravity.CENTER);
        textView.setText("Content: " + position);
        contentContainer.addView(textView);
        container.addView(contentContainer);
        return contentContainer;
    }

    @Override
    public boolean isViewFromObject(View view, Object object) {
        return view == object;
    }

    @Override
    public void destroyItem(ViewGroup container, int position, Object object) {
        if (object instanceof RelativeLayout) {
            RelativeLayout view = (RelativeLayout) object;
            view.removeAllViews();
            container.removeView(view);
        }
    }

// Usage:

// Runs within onCreate()
UltraViewPager myViewPager = findViewById(R.id.view_pager);
MyAdapter myAdapter = new MyAdapter(this/*context*/);
myViewPager.setAdapter(myAdapter); myViewPager.setScrollMode(UltraViewPager.ScrollMode.HORIZONTAL);
myViewPager.setMultiScreen(0.7f);
myViewPager.setItemRatio(1.0f);
myViewPager.setAutoScroll(10000);
myViewPager.setPageTransformer(false, new UltraDepthScaleTransformer());

// Runs after data loaded from server (in the future):
myAdapter.addData(myData)

```

**Comment by urtheone** [comment]
i have this problem also

**Comment by longerian** [comment]
try calling `disableAutoScroll` first.

**Comment by srfaytkn** [comment]
+1

**Comment by jemshit** [comment]
Any workaround ?

**Comment by BIGMONK** [comment]
+1

**Comment by MikeAfc** [comment]
Have added method to help refresh data. See faq to learn more:
https://github.com/alibaba/UltraViewPager/wiki/FAQ
https://github.com/alibaba/UltraViewPager#faq

**Comment by JayeshDankhara** [comment]
i have same error with viewpager.
any one help to how to resolve this...

**Comment by louiewh** [comment]
+1
