### ISSUE TITLE
UltraViewPagerAdapter.getCount()' on a null object reference

### ISSUE THREAD

**Issue by prasad456** [alibaba/UltraViewPager#82]
Hi,

I implemented ultra view pager adapter, i had issues where list has items

`java.lang.NullPointerException: Attempt to invoke virtual method 'int com.tmall.ultraviewpager.UltraViewPagerAdapter.getCount()' on a null object reference
                                                                        at com.tmall.ultraviewpager.UltraViewPagerView.getCurrentItem(UltraViewPagerView.java:217)
                                                                        at com.tmall.ultraviewpager.UltraViewPagerView.onMeasurePage(UltraViewPagerView.java:86)
                                                                        at com.tmall.ultraviewpager.UltraViewPagerView.onMeasure(UltraViewPagerView.java:82)
                                                                        at android.view.View.measure(View.java:19826)
                                                                        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                        at com.tmall.ultraviewpager.UltraViewPager.onMeasure(UltraViewPager.java:179)
                                                                        at android.view.View.measure(View.java:19826)
                                                                        at android.support.constraint.ConstraintLayout.internalMeasureChildren(ConstraintLayout.java:934)
                                                                        at android.support.constraint.ConstraintLayout.onMeasure(ConstraintLayout.java:973)
                                                                        at android.view.View.measure(View.java:19826)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6164)
                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                        at android.view.View.measure(View.java:19826)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6164)
                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                        at android.view.View.measure(View.java:19826)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6164)
                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                        at android.view.View.measure(View.java:19826)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6164)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                        at android.support.v7.widget.CardView.onMeasure(CardView.java:219)
                                                                        at android.view.View.measure(View.java:19826)
                                                                        at android.support.constraint.ConstraintLayout.internalMeasureChildren(ConstraintLayout.java:934)
                                                                        at android.support.constraint.ConstraintLayout.onMeasure(ConstraintLayout.java:973)
                                                                        at android.view.View.measure(View.java:19826)
                                                                        at android.support.v7.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:8765)
                                                                        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1582)
                                                                        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1516)
                                                                        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:608)
                                                                        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3693)
                                                                        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3410)
                                                                        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3962)
                                                                        at android.view.View.layout(View.java:17564)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5656)
                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                        at android.view.View.layout(View.java:17564)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5656)
                                                                        at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1166)
                                                                        at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:851)
                                                                        at android.support.design.widget.ViewOffsetBehavior.layoutChild(ViewOffsetBehavior.java:63)
                                                                        at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:136)
                                                                        at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
03-14 12:29:50.359 29525-29525/com.ebiz.liftptich E/AndroidRuntime:     at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1361)
                                                                        at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:869)
                                                                        at android.view.View.layout(View.java:17564)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5656)
                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                        at android.view.View.layout(View.java:17564)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5656)
                                                                        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                        at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                        at android.view.View.layout(View.java:17564)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5656)
                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                        at android.view.View.layout(View.java:17564)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5656)
                                                                        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                        at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                        at android.view.View.layout(View.java:17564)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5656)
                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                        at com.android.internal.policy.DecorView.onLayout(DecorView.java:755)
                                                                        at android.view.View.layout(View.java:17564)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5656)
                                                                        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2422)
                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2142)
                                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1299)
                                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6558)
                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:683)
                                                                        at android.view.Choreographer.doFrame(Choreographer.java:619)
                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
                                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6316)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)`

**Comment by xinychan** [comment]
碰到同样的问题。
如果仅仅在xml中声明了UltraViewPager，但代码里面并没有使用到它，进入界面会直接报这个错误。可将UltraViewPager设置为Gone，这个错误就不会触发；当获取完数据，并设置好UltraViewPagerAdapter后，再将UltraViewPager设置为Visible，可避免这个错误。
但从Gone到Visible后，UltraViewPager显示图片有错误，要滑动2个banner后，imageview才能正常显示图片，前面两个imageview仅显示UltraViewPager的background，滑到第3个才正常。
我的例子是总共5个imageview，显示5张不同图片。

**Comment by MikeAfc** [comment]
@xinychan 使用的版本是？我模拟的场景是先 new 一个 UltraViewPager，什么都不做，然后在点击某个按钮后再new adapter，以及塞数据，没有问题，这个case是否没覆盖到你的场景？

**Comment by xinychan** [comment]
@MikeAfc 
使用的版本_1.0.6.1
场景是，在xml布局中使用UltraViewPager，然后什么都不做，运行界面就会报错。

**Comment by MikeAfc** [comment]
Fixed on latest version (1.0.7.1).

**Comment by DavikChen** [comment]
确认完全修复了吗 ？发现问题依旧存在啊   采用@xinychan 说的 可以解决奔溃

**Comment by MikeAfc** [comment]
@DavikChen D 1.0.7.1发布有点小问题，重新发布了1.0.7.6
