### ISSUE TITLE
使用 FragmentPagerAdapter 时抛出异常 java.lang.IllegalStateException: ViewPager with adapter XXX requires a view id

### ISSUE THREAD

**Issue by nex3z** [alibaba/UltraViewPager#9]
在 `UltraViewPager` 的 `setAdapter()` 中使用 `FragmentPagerAdapter` 时抛出 `java.lang.IllegalStateException` 异常，信息如下：

Process: test.fragmentpagerdemo, PID: 26425
java.lang.IllegalStateException: ViewPager with adapter test.fragmentpagerdemo.MainActivity$NumberFragmentPagerAdapter@23052a8 requires a view id
	at android.support.v4.app.FragmentPagerAdapter.startUpdate(FragmentPagerAdapter.java:81)
	at com.tmall.ultraviewpager.UltraViewPagerAdapter.startUpdate(UltraViewPagerAdapter.java:189)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1148)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
	at com.tmall.ultraviewpager.UltraViewPagerView.onMeasure(UltraViewPagerView.java:83)
	at android.view.View.measure(View.java:19740)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
	at com.tmall.ultraviewpager.UltraViewPager.onMeasure(UltraViewPager.java:170)
	at android.view.View.measure(View.java:19740)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:19740)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
...

复现代码见[这里](https://github.com/nex3z/UltraViewPager/blob/sample/fragment_pager_adapter/fragmentpagerdemo/src/main/java/test/fragmentpagerdemo/MainActivity.java#L37)。

`FragmentPagerAdapter` 要求 `ViewPager` [具有一个 id](https://android.googlesource.com/platform/frameworks/support/+/refs/heads/master/v13/java/android/support/v13/app/FragmentPagerAdapter.java#88)，`UltraViewPager` 里的 `UltraViewPagerView` [没有 id](https://github.com/alibaba/UltraViewPager/blob/master/ultraviewpager/src/main/java/com/tmall/ultraviewpager/UltraViewPager.java#L129)，导致此异常。

**Comment by MikeAfc** [comment]
建议通过 com.tmall.ultraviewpager.UltraViewPager#getViewPager 设置id
